language: python

python:
  - "3.5"

sudo: true

before_script:
  - pip install -r test-requirements.txt
  - sudo apt-get install -y python3-gi python3-gi-cairo libglib2.0-dev libffi-dev libgirepository1.0 libcairo2-dev python3-cairo-dev
  - python setup.py install

script:
  - coala-ci
  - pytest --cov

after_success:
  - bash <(curl -s https://codecov.io/bash)
